spring:
  config:
    activate:
      on-profile: set1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(l99MJqAUPwKvze+lJpIq8F9T+dfHg9TTE0qKgyM2jk5o0hMR6RB1SNRkdOdqBqqR0Gw0xUgjTKCo5ShUQm6TQJvnqO+NbjP2hGlXwGGgnPo0lZZKQO5Hm0O08AiU8/VYC8Vmb7xdx7ZIKfYSGgpdcHX/ifN5dceHEOLUjuxinRdQVap8gtUiHqbLDCoLIKXz8xLOOlyQnvg=)
    username: ENC(fYM/g4oPrAc9UX8Ei9BGbEaFpbjXtvU2)
    password: ENC(xA+qzw+zb/hMNOSQdVbT4/dOiGmPZkrR)

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(qf7lBciaiT8g3XhVYn+i/PyAq6nqi+CWPtEIPdQszAlfMsdlXIIwuaWr53cP7kkg)
            client-secret: ENC(RetuLPjf6u32+kBdvp4ziHTXkpXY0FQUq6owb+TBPybExx4hQyL9qxgYrBNdsP/6)
            redirect-uri: ENC(gz+110oQVeBuAPODt8RXUHn7wcaYoyZ6+Z6wDhh0Aj6qtwGDsPf4IgCIopIyu4GJdh+b9AqZaVw=)
            authorization-grant-type: ENC(jIb8yhXuUej6dLo4GMYaZTdJ5qEvL/9eHlXV5m+Y0QA=)
            client-authentication-method: ENC(Y5v97pWe1W3zTNzxXqPFow==)
            scope: ENC(XaFAnflllxuKjX5NN0v5BsH5EymZTfqKFC/Ap0r88HQ=)

          naver:
            client-id: ENC(V8YybimxtjzfJm3KE6sMfUMUVfV68cHHdKUI1XZdv0I=)
            client-secret: ENC(yFUo3FTia2QSAC7dFZsyPAq7uvfnewed)
            redirect-uri: ENC(DhsxL6pnsbgd8BLQVNxAS1HDWzmOb9r6oBorvf7AuyLqNT3Ma1Gt36XQHAcnj52TiTsT9MA8gy4=))
            authorization-grant-type: ENC(RKNd4gFhDjstXA+BSAipzCo+xsttUAdm8M+qB2m1lC4=)
            scope: ENC(VdCWI/YUyCe+/eQ3MI2F2Zp/pkUGcuYE)
            client-name: Naver

        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

jasypt:
  encryptor:
    bean : jasyptStringEncryptor

gpt:
  key: ENC(Jzyf0nsLehjSuR1auVWcle/+yw4FYRSatil6ylkRnvh73RJM03nNp6ECWy+VWDTo4xABNNlrhIJpsnpiiGkilQ==)

server:
  port: 8081

springdoc:
  version: v1
  packages-to-scan: com.example.cherrypickserver
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html            # Swagger UI 경로 => localhost:8081/swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    doc-expansion: none
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true


jwt:
  secret-key: ENC(dQZ/q7TpH28bAirCy2d90W9Px/J9Hut1xSwYxoluJNcXlluq/YYkpkX9n3ECUtjjMs/SpYjJMfU90NWadmL0Y3K3CWFM+zY2HgphrmLbqEPCgebPyyJ52pRGWrdBR1i4qwcpPQT32a6vg+DYIhrurYWVNk7Oj+Syi6jexuxccmXmmHfvP4M3B6ozPVEFcSvi)
  issuer: cherrypick app

  access:
    expiration: 3600000
    header: Authorization

---

spring:
  config:
    activate:
      on-profile: set2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(l99MJqAUPwKvze+lJpIq8F9T+dfHg9TTE0qKgyM2jk5o0hMR6RB1SNRkdOdqBqqR0Gw0xUgjTKCo5ShUQm6TQJvnqO+NbjP2hGlXwGGgnPo0lZZKQO5Hm0O08AiU8/VYC8Vmb7xdx7ZIKfYSGgpdcHX/ifN5dceHEOLUjuxinRdQVap8gtUiHqbLDCoLIKXz8xLOOlyQnvg=)
    username: ENC(fYM/g4oPrAc9UX8Ei9BGbEaFpbjXtvU2)
    password: ENC(xA+qzw+zb/hMNOSQdVbT4/dOiGmPZkrR)

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(qf7lBciaiT8g3XhVYn+i/PyAq6nqi+CWPtEIPdQszAlfMsdlXIIwuaWr53cP7kkg)
            client-secret: ENC(RetuLPjf6u32+kBdvp4ziHTXkpXY0FQUq6owb+TBPybExx4hQyL9qxgYrBNdsP/6)
            redirect-uri: ENC(gz+110oQVeBuAPODt8RXUHn7wcaYoyZ6+Z6wDhh0Aj6qtwGDsPf4IgCIopIyu4GJdh+b9AqZaVw=)
            authorization-grant-type: ENC(jIb8yhXuUej6dLo4GMYaZTdJ5qEvL/9eHlXV5m+Y0QA=)
            client-authentication-method: ENC(Y5v97pWe1W3zTNzxXqPFow==)
            scope: ENC(XaFAnflllxuKjX5NN0v5BsH5EymZTfqKFC/Ap0r88HQ=)

          naver:
            client-id: ENC(V8YybimxtjzfJm3KE6sMfUMUVfV68cHHdKUI1XZdv0I=)
            client-secret: ENC(yFUo3FTia2QSAC7dFZsyPAq7uvfnewed)
            redirect-uri: ENC(DhsxL6pnsbgd8BLQVNxAS1HDWzmOb9r6oBorvf7AuyLqNT3Ma1Gt36XQHAcnj52TiTsT9MA8gy4=)
            authorization-grant-type: ENC(RKNd4gFhDjstXA+BSAipzCo+xsttUAdm8M+qB2m1lC4=)
            scope: ENC(VdCWI/YUyCe+/eQ3MI2F2Zp/pkUGcuYE)
            client-name: Naver

        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

jasypt:
  encryptor:
    bean : jasyptStringEncryptor

gpt:
  key: ENC(Jzyf0nsLehjSuR1auVWcle/+yw4FYRSatil6ylkRnvh73RJM03nNp6ECWy+VWDTo4xABNNlrhIJpsnpiiGkilQ==)
server:
  port: 8082


jwt:
  secret-key: ENC(dQZ/q7TpH28bAirCy2d90W9Px/J9Hut1xSwYxoluJNcXlluq/YYkpkX9n3ECUtjjMs/SpYjJMfU90NWadmL0Y3K3CWFM+zY2HgphrmLbqEPCgebPyyJ52pRGWrdBR1i4qwcpPQT32a6vg+DYIhrurYWVNk7Oj+Syi6jexuxccmXmmHfvP4M3B6ozPVEFcSvi)
  issuer: cherrypick app

  access:
    expiration: 3600000
    header: Authorization
